modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "sedna"
version = "${file.jarVersion}"
displayName = "Sedna for Minecraft"
logoFile = "logo.png"
authors = "Sangar"
description = '''
RISC-V Virtual Machine and binary images for computer mods.
'''

[[dependencies.oc2-sedna]]
modId = "forge"
mandatory = true
versionRange = "[36.1.13,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.oc2-sedna]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
