modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "sedna"
version = "${file.jarVersion}"
displayName = "Sedna for Minecraft"
logoFile = "logo.png"
authors = "Sangar"
description = '''
RISC-V Virtual Machine and binary images for computer mods.

This mod contains a Linux distribution built from the following repository:

  https://github.com/Un1q32/buildroot

The licenses for the embedded software are embedded in the JAR file containing this mod, inside the "licenses" directory.
'''

[[dependencies.oc2-sedna]]
modId = "forge"
mandatory = true
versionRange = "[47.3.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.oc2-sedna]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
